[workspace]
resolver = "2"
members = [
    "days/day1",
    "days/day2",
    "days/day3",
    "days/day4",
    "days/day5",
    "days/day6",
    "days/day7",
    "days/day8",
    "days/day9",
    "days/day10",
    "days/day11",
]
